#include "views/full_table.h"

#include "views/common.h"

#include "state.h"

#include "imgui.h"

void full_table_draw(const StateSnapshot &state) {
  ImGui::Begin("Full Table", nullptr, COMMON_VIEW_FLAGS);
  if (ImGui::BeginTable("Stats", 52,
                        ImGuiTableFlags_Resizable |
                            ImGuiTableFlags_NoSavedSettings |
                            ImGuiTableFlags_Borders)) {
    ImGui::TableNextColumn();
    ImGui::Text("pid");
    ImGui::TableNextColumn();
    ImGui::Text("comm");
    ImGui::TableNextColumn();
    ImGui::Text("state");
    ImGui::TableNextColumn();
    ImGui::Text("ppid");
    ImGui::TableNextColumn();
    ImGui::Text("pgrp");
    ImGui::TableNextColumn();
    ImGui::Text("session");
    ImGui::TableNextColumn();
    ImGui::Text("tty_nr");
    ImGui::TableNextColumn();
    ImGui::Text("tpgid");
    ImGui::TableNextColumn();
    ImGui::Text("flags");
    ImGui::TableNextColumn();
    ImGui::Text("minflt");
    ImGui::TableNextColumn();
    ImGui::Text("cminflt");
    ImGui::TableNextColumn();
    ImGui::Text("majflt");
    ImGui::TableNextColumn();
    ImGui::Text("cmajflt");
    ImGui::TableNextColumn();
    ImGui::Text("utime");
    ImGui::TableNextColumn();
    ImGui::Text("stime");
    ImGui::TableNextColumn();
    ImGui::Text("cutime");
    ImGui::TableNextColumn();
    ImGui::Text("cstime");
    ImGui::TableNextColumn();
    ImGui::Text("priority");
    ImGui::TableNextColumn();
    ImGui::Text("nice");
    ImGui::TableNextColumn();
    ImGui::Text("num_threads");
    ImGui::TableNextColumn();
    ImGui::Text("itrealvalue");
    ImGui::TableNextColumn();
    ImGui::Text("starttime");
    ImGui::TableNextColumn();
    ImGui::Text("vsize");
    ImGui::TableNextColumn();
    ImGui::Text("rss");
    ImGui::TableNextColumn();
    ImGui::Text("rsslim");
    ImGui::TableNextColumn();
    ImGui::Text("startcode");
    ImGui::TableNextColumn();
    ImGui::Text("endcode");
    ImGui::TableNextColumn();
    ImGui::Text("startstack");
    ImGui::TableNextColumn();
    ImGui::Text("kstkesp");
    ImGui::TableNextColumn();
    ImGui::Text("kstkeip");
    ImGui::TableNextColumn();
    ImGui::Text("signal");
    ImGui::TableNextColumn();
    ImGui::Text("blocked");
    ImGui::TableNextColumn();
    ImGui::Text("sigignore");
    ImGui::TableNextColumn();
    ImGui::Text("sigcatch");
    ImGui::TableNextColumn();
    ImGui::Text("wchan");
    ImGui::TableNextColumn();
    ImGui::Text("nswap");
    ImGui::TableNextColumn();
    ImGui::Text("cnswap");
    ImGui::TableNextColumn();
    ImGui::Text("exit_signal");
    ImGui::TableNextColumn();
    ImGui::Text("processor");
    ImGui::TableNextColumn();
    ImGui::Text("rt_priority");
    ImGui::TableNextColumn();
    ImGui::Text("policy");
    ImGui::TableNextColumn();
    ImGui::Text("delayacct_blkio_ticks");
    ImGui::TableNextColumn();
    ImGui::Text("guest_time");
    ImGui::TableNextColumn();
    ImGui::Text("cguest_time");
    ImGui::TableNextColumn();
    ImGui::Text("start_data");
    ImGui::TableNextColumn();
    ImGui::Text("end_data");
    ImGui::TableNextColumn();
    ImGui::Text("start_brk");
    ImGui::TableNextColumn();
    ImGui::Text("arg_start");
    ImGui::TableNextColumn();
    ImGui::Text("arg_end");
    ImGui::TableNextColumn();
    ImGui::Text("env_start");
    ImGui::TableNextColumn();
    ImGui::Text("env_end");
    ImGui::TableNextColumn();
    ImGui::Text("exit_code");

    for (size_t i = 0; i < state.stats.size; ++i) {
      const ProcessStat &stat = state.stats.data[i];
      ImGui::TableNextColumn();
      ImGui::Text("%d", stat.pid);
      ImGui::TableNextColumn();
      ImGui::Text("%s", stat.comm);
      ImGui::TableNextColumn();
      ImGui::Text("%c", stat.state);
      ImGui::TableNextColumn();
      ImGui::Text("%d", stat.ppid);
      ImGui::TableNextColumn();
      ImGui::Text("%d", stat.pgrp);
      ImGui::TableNextColumn();
      ImGui::Text("%d", stat.session);
      ImGui::TableNextColumn();
      ImGui::Text("%d", stat.tty_nr);
      ImGui::TableNextColumn();
      ImGui::Text("%d", stat.tpgid);
      ImGui::TableNextColumn();
      ImGui::Text("%u", stat.flags);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.minflt);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.cminflt);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.majflt);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.cmajflt);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.utime);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.stime);
      ImGui::TableNextColumn();
      ImGui::Text("%ld", stat.cutime);
      ImGui::TableNextColumn();
      ImGui::Text("%ld", stat.cstime);
      ImGui::TableNextColumn();
      ImGui::Text("%ld", stat.priority);
      ImGui::TableNextColumn();
      ImGui::Text("%ld", stat.nice);
      ImGui::TableNextColumn();
      ImGui::Text("%ld", stat.num_threads);
      ImGui::TableNextColumn();
      ImGui::Text("%ld", stat.itrealvalue);
      ImGui::TableNextColumn();
      ImGui::Text("%llu", stat.starttime);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.vsize);
      ImGui::TableNextColumn();
      ImGui::Text("%ld", stat.rss);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.rsslim);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.startcode);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.endcode);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.startstack);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.kstkesp);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.kstkeip);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.signal);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.blocked);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.sigignore);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.sigcatch);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.wchan);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.nswap);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.cnswap);
      ImGui::TableNextColumn();
      ImGui::Text("%d", stat.exit_signal);
      ImGui::TableNextColumn();
      ImGui::Text("%d", stat.processor);
      ImGui::TableNextColumn();
      ImGui::Text("%u", stat.rt_priority);
      ImGui::TableNextColumn();
      ImGui::Text("%u", stat.policy);
      ImGui::TableNextColumn();
      ImGui::Text("%llu", stat.delayacct_blkio_ticks);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.guest_time);
      ImGui::TableNextColumn();
      ImGui::Text("%ld", stat.cguest_time);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.start_data);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.end_data);
      ImGui::Text("%lu", stat.start_brk);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.arg_start);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.arg_end);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.env_start);
      ImGui::TableNextColumn();
      ImGui::Text("%lu", stat.env_end);
      ImGui::TableNextColumn();
      ImGui::Text("%d", stat.exit_code);
      ImGui::TableNextColumn();
    }

    ImGui::EndTable();
  }

  ImGui::End();
}
