// Generated by scripts/gen_icons.py - do not edit.
// Codepoints for the Material Symbols glyphs embedded in
// third-party/material-symbols/material_symbols_font.h (Apache-2.0).
#pragma once

// Material Symbols glyphs merged into the UI font by load_fonts().
#define ICON_MIN_MD 0xe14d
#define ICON_MAX_MD 0xef7a

#define ICON_MD_CONTENT_COPY "\xee\x85\x8d"
#define ICON_MD_FILTER_ALT   "\xee\xbd\x8f"
#define ICON_MD_SHOW_CHART   "\xee\x9b\xa1"
#define ICON_MD_SEARCH       "\xee\xbd\xba"
#define ICON_MD_SETTINGS     "\xee\xa2\xb8"
#define ICON_MD_DELETE       "\xee\xa4\xae"
