#!/usr/bin/env python3
"""Regenerate the embedded license texts as a C header.

Run::

    python3 scripts/gen_licenses.py

Emits prock's own LICENSE plus the verbatim LICENSE of every third-party library,
font, and theme palette bundled into the binary, as raw string literals in
src/views/licenses.h. The "Licenses" dialog (src/views/menu_bar.cpp) renders them,
so the single binary carries every notice MIT, OFL 1.1, and Apache-2.0 require.

Tracy is omitted: the publish preset builds with ENABLE_TRACY=OFF.

Generated (committed) output:
    src/views/licenses.h
"""

import json
import pathlib
import re

REPO = pathlib.Path(__file__).resolve().parent.parent


def font_copyright(header_rel):
    """Return the 'Copyright ...' line that gen_font.py / gen_icons.py extracted
    verbatim from the font's name table into the generated header's comment."""
    for line in (REPO / "third-party" / header_rel).read_text("utf-8").splitlines():
        m = re.match(r"//\s*(Copyright .+)", line)
        if m:
            return m.group(1).strip()
    raise SystemExit(f"no copyright comment in third-party/{header_rel}")


# (display name, LICENSE path relative to third-party/, copyright notice or None),
# in display order: libraries first, then fonts, then theme palettes. Tracy is
# omitted on purpose (see module docstring). The MIT/zlib/OFL texts already lead
# with their copyright line, so they need no prefix. The Apache-2.0 text, however,
# is a generic template that names no holder, so Material Symbols' notice is
# prepended from the font name table (Apache-2.0 sec. 4 keeps the attribution with
# the work).
LIBRARIES = [
    ("Dear ImGui", "imgui/LICENSE.txt", None),
    ("ImPlot", "implot/LICENSE", None),
    ("GLFW", "glfw-3.4/LICENSE.md", None),
    ("Inter", "inter/LICENSE", None),
    ("JetBrains Mono", "jetbrains-mono/LICENSE", None),
    ("Material Symbols", "material-symbols/LICENSE",
     font_copyright("material-symbols/material_symbols_font.h")),
    # Theme palettes reimplemented as color values in src/themes.h. The values
    # themselves are data, but we ship the upstream MIT notice to credit each
    # palette's authors. Nord covers OneNord's structure; Atom One Dark covers its
    # accents.
    ("Everforest", "everforest/LICENSE", None),
    ("Nord", "nord/LICENSE", None),
    ("Atom One Dark", "atom-one-dark/LICENSE", None),
]

# Raw-string delimiter; chosen so it cannot collide with license body text.
DELIM = "LIC"
OUT = REPO / "src/views/licenses.h"


def check_delim(text, where):
    if f"){DELIM}\"" in text:
        raise SystemExit(f'raw-string delimiter )"{DELIM} appears in {where}')
    return text


def main():
    # Prock's own MIT text. The About dialog shows the copyright line and links to
    # the full text, so a fork or a repackaged build carries the notice MIT
    # requires even when no LICENSE file sits beside the binary.
    prock = check_delim((REPO / "LICENSE").read_text(encoding="utf-8"), "LICENSE")
    m = re.search(r"^Copyright \(c\) .+$", prock, re.MULTILINE)
    if not m:
        raise SystemExit("no copyright line in LICENSE")
    prock_copyright = m.group(0).strip()

    entries = []
    for name, rel, notice in LIBRARIES:
        text = (REPO / "third-party" / rel).read_text(encoding="utf-8")
        if notice:
            text = f"{notice}\n\n{text}"
        entries.append((name, check_delim(text, rel)))

    lines = [
        "// Generated by scripts/gen_licenses.py - do not edit.",
        "// Verbatim license texts for prock and for the third-party libraries and",
        '// fonts bundled into the binary, shown by the "Licenses" dialog.',
        "#pragma once",
        "",
        f"static const char *PROCK_COPYRIGHT = "
        f"{json.dumps(prock_copyright, ensure_ascii=False)};",
        "",
        f'static const char *PROCK_LICENSE = R"{DELIM}({prock}){DELIM}";',
        "",
        "struct ThirdPartyLicense {",
        "  const char *name;",
        "  const char *text;",
        "};",
        "",
        "static const ThirdPartyLicense THIRD_PARTY_LICENSES[] = {",
    ]
    for name, text in entries:
        lines.append(f'    {{"{name}",')
        lines.append(f'     R"{DELIM}({text}){DELIM}"}},')
    lines.append("};")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(entries)} licenses)")


if __name__ == "__main__":
    main()
