#!/usr/bin/env python3
"""Regenerate the embedded Material Symbols icon font and its C macros.

To add or remove icons: edit ICONS below, then run::

    python3 scripts/gen_icons.py

The Google Fonts API instances and subsets the font server-side, so this needs
only network access and the Python standard library (no fonttools, no compiler).
The generated headers are committed, so the normal build needs nothing. Browse
icon names at https://fonts.google.com/icons

Material Symbols is licensed under the Apache License 2.0. The embedded copy is a
modified (instanced + subset) version of the upstream font; the full license text
lives in third-party/material-symbols/LICENSE. The font header carries an
attribution comment whose copyright line is read verbatim from the font's own
name table (Apache-2.0 sec. 4 requirements); icons.h only maps codepoints, so it
just points back at the font.

Generated (committed) outputs:
    third-party/material-symbols/material_symbols_font.h  subset TTF as a byte array
    src/views/icons.h                ICON_MD_* UTF-8 macros + ICON_MIN/MAX_MD range
"""

import pathlib
import re
import urllib.request

# --- Icons to embed (Material Symbols glyph names) -------------------------
ICONS = ["content_copy", "filter_alt", "show_chart", "search", "settings",
         "delete"]

# Static cut of the variable font requested from the API (axis @ values).
AXES = "opsz,wght,FILL,GRAD@24,400,0,0"

REPO = pathlib.Path(__file__).resolve().parent.parent

def read_copyright(ttf):
    """Return the verbatim copyright notice (name table ID 0) from the font.

    The Apache license template names no owner; the real notice lives in the
    font's metadata, so we read it straight from the bytes we embed.
    """
    def u16(o):
        return int.from_bytes(ttf[o:o + 2], "big")

    def u32(o):
        return int.from_bytes(ttf[o:o + 4], "big")

    name_off = None
    for i in range(u16(4)):  # numTables
        rec = 12 + i * 16
        if ttf[rec:rec + 4] == b"name":
            name_off = u32(rec + 8)
            break
    if name_off is None:
        raise SystemExit("error: font has no 'name' table")

    storage = name_off + u16(name_off + 4)
    best = None  # (priority, text); prefer Windows/Unicode records over Mac
    for i in range(u16(name_off + 2)):  # count
        r = name_off + 6 + i * 12
        platform, name_id = u16(r), u16(r + 6)
        if name_id != 0:  # 0 = copyright notice
            continue
        raw = ttf[storage + u16(r + 10):storage + u16(r + 10) + u16(r + 8)]
        if platform in (0, 3):  # Unicode / Windows -> UTF-16BE
            text, priority = raw.decode("utf-16-be", "replace"), 2
        else:                   # Macintosh and others -> Latin-1 approximation
            text, priority = raw.decode("latin-1", "replace"), 1
        if best is None or priority > best[0]:
            best = (priority, text)
    if best is None:
        raise SystemExit("error: font has no copyright notice (name ID 0)")
    return best[1].strip()


def attribution(copyright_notice):
    """C comment stamped into every generated header.

    Material Symbols is Apache-2.0 and the embedded data is a modified
    (instanced + subset) cut, so each file names the source, retains the font's
    own copyright notice, states the change, and points at the license text
    (Apache-2.0 sec. 4 a/b/c).
    """
    return (
        "// Generated by scripts/gen_icons.py - do not edit.\n"
        "//\n"
        "// Contains Material Symbols (Outlined), modified by instancing to fixed\n"
        "// axes and subsetting to the icons used here.\n"
        f"// {copyright_notice}\n"
        "// Licensed under Apache-2.0; see third-party/material-symbols/LICENSE.\n"
    )

_CSS_URL = ("https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:"
            + AXES + "&icon_names=")
_CODEPOINTS_URL = (
    "https://raw.githubusercontent.com/google/material-design-icons/master/"
    "variablefont/MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints")


def fetch(url):
    # A browser User-Agent keeps the API consistent; it still returns TrueType
    # (not woff2) when icon_names + pinned axes are requested.
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=120) as resp:
        return resp.read()


def download_subset_ttf():
    # The css2 API requires icon_names to be sorted, else it returns HTTP 400.
    css = fetch(_CSS_URL + ",".join(sorted(ICONS))).decode()
    ttf_url = re.search(r"src:\s*url\(([^)]+)\)\s*format\('truetype'\)", css).group(1)
    return fetch(ttf_url)


def resolve_codepoints():
    """Map each icon name to its codepoint, preserving ICONS order."""
    table = {}
    for line in fetch(_CODEPOINTS_URL).decode().splitlines():
        parts = line.split()
        if len(parts) == 2:
            table[parts[0]] = int(parts[1], 16)
    resolved = []
    for name in ICONS:
        if name not in table:
            raise SystemExit(f"error: icon '{name}' not found in codepoints map")
        resolved.append((name, table[name]))
        print(f"  {name} -> U+{table[name]:04x}")
    return resolved


def write_font_header(ttf, attrib):
    rows = []
    for i in range(0, len(ttf), 12):
        rows.append("    " + " ".join(f"0x{b:02x}," for b in ttf[i:i + 12]))
    body = "\n".join(rows)
    text = (
        attrib +
        "#pragma once\n\n"
        "static const unsigned char material_symbols_ttf[] = {\n"
        f"{body}\n"
        "};\n"
        "static const int material_symbols_ttf_size = (int)sizeof(material_symbols_ttf);\n"
    )
    out = REPO / "third-party/material-symbols/material_symbols_font.h"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)


def write_macros(codepoints):
    entries = []
    for name, cp in codepoints:
        utf8 = "".join(f"\\x{b:02x}" for b in chr(cp).encode("utf-8"))
        entries.append((f"ICON_MD_{name.upper()}", cp, utf8))
    cps = [cp for _, cp, _ in entries]
    width = max(len(macro) for macro, _, _ in entries)
    # Just codepoint mappings (not the copyrighted font data), so this carries a
    # pointer rather than the full attribution block; that lives on the font.
    lines = [
        "// Generated by scripts/gen_icons.py - do not edit.",
        "// Codepoints for the Material Symbols glyphs embedded in",
        "// third-party/material-symbols/material_symbols_font.h (Apache-2.0).",
        "#pragma once",
        "",
        "// Material Symbols glyphs merged into the UI font by load_fonts().",
        f"#define ICON_MIN_MD 0x{min(cps):04x}",
        f"#define ICON_MAX_MD 0x{max(cps):04x}",
        "",
    ]
    lines += [f'#define {macro:<{width}} "{utf8}"' for macro, _, utf8 in entries]
    (REPO / "src/views/icons.h").write_text("\n".join(lines) + "\n")


def main():
    print("Resolving codepoints...")
    codepoints = resolve_codepoints()

    print("Downloading subset font...")
    ttf = download_subset_ttf()
    print(f"  subset TTF: {len(ttf)} bytes")

    notice = read_copyright(ttf)
    print(f"  copyright: {notice}")
    attrib = attribution(notice)

    write_font_header(ttf, attrib)
    write_macros(codepoints)

    print("Done:")
    print("  third-party/material-symbols/material_symbols_font.h")
    print("  src/views/icons.h")


if __name__ == "__main__":
    main()
