#!/usr/bin/env python3
"""Regenerate the embedded third-party license texts as a C header.

Run::

    python3 scripts/gen_licenses.py

Reads the verbatim LICENSE file shipped with each third-party library and font
bundled into the binary, plus the upstream LICENSE for each theme palette adapted
into src/themes.h, and emits them as raw string literals in src/views/licenses.h.
The "Third-Party Licenses" dialog (src/views/menu_bar.cpp) renders these, so the
portable binary carries its own attribution and satisfies the MIT (Dear ImGui,
ImPlot, and the Everforest/Nord/Atom One Dark theme palettes), SIL OFL 1.1
(Inter), and Apache-2.0 (Material Symbols) notice requirements. GLFW's zlib
license is included for consistency, though it only appreciates (does not require)
acknowledgment.

Tracy is intentionally omitted: the publish preset builds with ENABLE_TRACY=OFF,
so its code is not present in the distributed binary.

Generated (committed) output:
    src/views/licenses.h
"""

import pathlib
import re

REPO = pathlib.Path(__file__).resolve().parent.parent


def font_copyright(header_rel):
    """Return the 'Copyright ...' line that gen_font.py / gen_icons.py extracted
    verbatim from the font's name table into the generated header's comment."""
    for line in (REPO / "third-party" / header_rel).read_text("utf-8").splitlines():
        m = re.match(r"//\s*(Copyright .+)", line)
        if m:
            return m.group(1).strip()
    raise SystemExit(f"no copyright comment in third-party/{header_rel}")


# (display name, LICENSE path relative to third-party/, copyright notice or None),
# in display order: libraries first, then fonts, then theme palettes. Tracy is
# omitted on purpose (see module docstring). The MIT/zlib/OFL texts already lead
# with their copyright line, so they need no prefix. The Apache-2.0 text, however,
# is a generic template that names no holder, so Material Symbols' notice is
# prepended from the font name table (Apache-2.0 sec. 4 keeps the attribution with
# the work).
LIBRARIES = [
    ("Dear ImGui", "imgui/LICENSE.txt", None),
    ("ImPlot", "implot/LICENSE", None),
    ("GLFW", "glfw-3.4/LICENSE.md", None),
    ("Inter", "inter/LICENSE", None),
    ("JetBrains Mono", "jetbrains-mono/LICENSE", None),
    ("Material Symbols", "material-symbols/LICENSE",
     font_copyright("material-symbols/material_symbols_font.h")),
    # Theme palettes reimplemented as color values in src/themes.h. The values
    # themselves are data, but we ship the upstream MIT notice to credit each
    # palette's authors. Nord covers OneNord's structure; Atom One Dark covers its
    # accents.
    ("Everforest", "everforest/LICENSE", None),
    ("Nord", "nord/LICENSE", None),
    ("Atom One Dark", "atom-one-dark/LICENSE", None),
]

# Raw-string delimiter; chosen so it cannot collide with license body text.
DELIM = "LIC"
OUT = REPO / "src/views/licenses.h"


def main():
    entries = []
    for name, rel, notice in LIBRARIES:
        text = (REPO / "third-party" / rel).read_text(encoding="utf-8")
        if notice:
            text = f"{notice}\n\n{text}"
        if f"){DELIM}\"" in text:
            raise SystemExit(f'raw-string delimiter )"{DELIM} appears in {rel}')
        entries.append((name, text))

    lines = [
        "// Generated by scripts/gen_licenses.py - do not edit.",
        "// Verbatim license texts for the third-party libraries and fonts bundled",
        '// into the prock binary, shown by the "Third-Party Licenses" dialog.',
        "#pragma once",
        "",
        "struct ThirdPartyLicense {",
        "  const char *name;",
        "  const char *text;",
        "};",
        "",
        "static const ThirdPartyLicense THIRD_PARTY_LICENSES[] = {",
    ]
    for name, text in entries:
        lines.append(f'    {{"{name}",')
        lines.append(f'     R"{DELIM}({text}){DELIM}"}},')
    lines.append("};")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(entries)} licenses)")


if __name__ == "__main__":
    main()
