#!/usr/bin/env python3
"""Regenerate the embedded UI fonts as compressed C headers.

Run::

    python3 scripts/gen_font.py

For each font below, fetches the latest release from GitHub, takes the static
Regular cut, and runs it through Dear ImGui's binary_to_compressed_c tool. That
tool stb-compresses the TTF and base85-encodes it, so the committed header stays
a few hundred KB of source rather than a multi-megabyte byte array; load_fonts()
decodes it at startup with AddFontFromMemoryCompressedBase85TTF. Needs only
network access, a C++ compiler, and the Python standard library (no fonttools);
the generated headers are committed, so the normal build needs none of this.

Both fonts are licensed under the SIL Open Font License 1.1. The OFL permits
bundling and embedding; we ship each verbatim license next to its header, and
each header carries an attribution comment with the font's copyright line and a
pointer to that license.

Generated (committed) outputs, per font:
    third-party/<dir>/<symbol>_font.h  compressed+base85 TTF as a C string
    third-party/<dir>/LICENSE          verbatim SIL Open Font License 1.1
"""

import io
import json
import pathlib
import shutil
import subprocess
import tempfile
import urllib.request
import zipfile

REPO = pathlib.Path(__file__).resolve().parent.parent
TOOL_SRC = REPO / "third-party/imgui/misc/fonts/binary_to_compressed_c.cpp"

FONTS = [
    {
        "name": "Inter",
        "github_repo": "rsms/inter",
        "ttf_in_zip": "extras/ttf/Inter-Regular.ttf",
        "license_in_zip": "LICENSE.txt",
        "symbol": "inter",
        "out_dir": REPO / "third-party/inter",
        "cut_note": "static Regular instance",
    },
    {
        "name": "JetBrains Mono",
        "github_repo": "JetBrains/JetBrainsMono",
        "ttf_in_zip": "fonts/ttf/JetBrainsMono-Regular.ttf",
        "license_in_zip": "OFL.txt",
        "symbol": "jetbrains_mono",
        "out_dir": REPO / "third-party/jetbrains-mono",
        "cut_note": "Regular",
    },
]


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=180) as resp:
        return resp.read()


def latest_release_zip_url(github_repo):
    """Resolve the .zip asset of the most recent release, with its tag."""
    rel = json.loads(
        fetch(f"https://api.github.com/repos/{github_repo}/releases/latest"))
    for asset in rel["assets"]:
        if asset["name"].lower().endswith(".zip"):
            return asset["browser_download_url"], rel["tag_name"]
    raise SystemExit(f"error: no .zip asset on the latest {github_repo} release")


def copyright_line(license_text):
    """First 'Copyright' line of the OFL, used in the header's attribution."""
    for line in license_text.splitlines():
        if line.strip().lower().startswith("copyright"):
            return line.strip()
    raise SystemExit("error: no copyright line in font LICENSE")


def compress_to_base85(font, ttf, workdir):
    """Compile binary_to_compressed_c and run it on the TTF, returning its C output.

    The tool prints the input filename into a comment, so we run it from a temp
    dir on a cleanly named copy to keep absolute paths out of the committed file.
    """
    cxx = shutil.which("c++") or shutil.which("g++") or shutil.which("clang++")
    if not cxx:
        raise SystemExit("error: no C++ compiler found (need c++, g++, or clang++)")
    tool = workdir / "binary_to_compressed_c"
    subprocess.run([cxx, "-O2", str(TOOL_SRC), "-o", str(tool)], check=True)

    ttf_name = pathlib.Path(font["ttf_in_zip"]).name
    (workdir / ttf_name).write_bytes(ttf)
    out = subprocess.run([str(tool), "-base85", ttf_name, font["symbol"]],
                         cwd=workdir, check=True, capture_output=True, text=True)
    return out.stdout


def attribution(font, version, notice):
    rel_out = font["out_dir"].relative_to(REPO)
    return (
        "// Generated by scripts/gen_font.py - do not edit.\n"
        "//\n"
        f"// Contains {font['name']} ({version}, {font['cut_note']}), stb-compressed with\n"
        "// third-party/imgui/misc/fonts/binary_to_compressed_c.cpp and base85-encoded.\n"
        f"// {notice}\n"
        f"// Licensed under the SIL Open Font License 1.1; see {rel_out}/LICENSE.\n"
    )


def generate(font):
    print(f"Resolving latest {font['name']} release...")
    zip_url, version = latest_release_zip_url(font["github_repo"])
    print(f"  {version}: {zip_url}")

    print("Downloading release zip...")
    with zipfile.ZipFile(io.BytesIO(fetch(zip_url))) as zf:
        ttf = zf.read(font["ttf_in_zip"])
        license_text = zf.read(font["license_in_zip"]).decode()
    print(f"  {font['ttf_in_zip']}: {len(ttf)} bytes")

    print("Compressing font...")
    with tempfile.TemporaryDirectory() as tmp:
        c_array = compress_to_base85(font, ttf, pathlib.Path(tmp))

    out_dir = font["out_dir"]
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "LICENSE").write_text(license_text)
    header = (attribution(font, version, copyright_line(license_text)) +
              "#pragma once\n\n" + c_array)
    (out_dir / f"{font['symbol']}_font.h").write_text(header)
    print(f"  header: {len(header)} bytes")

    print("Done:")
    print(f"  {out_dir.relative_to(REPO)}/{font['symbol']}_font.h")
    print(f"  {out_dir.relative_to(REPO)}/LICENSE")


def main():
    for font in FONTS:
        generate(font)


if __name__ == "__main__":
    main()
