#!/usr/bin/env python3
"""Regenerate the embedded Inter UI font as a compressed C header.

Run::

    python3 scripts/gen_font.py

Fetches the latest Inter release from GitHub, takes the static Regular cut
(extras/ttf/Inter-Regular.ttf - the text-optimized family, not Display), and
runs it through Dear ImGui's binary_to_compressed_c tool. That tool stb-compresses
the TTF and base85-encodes it, so the committed header stays a few hundred KB of
source rather than a multi-megabyte byte array; load_fonts() decodes it at startup
with AddFontFromMemoryCompressedBase85TTF. Needs only network access, a C++
compiler, and the Python standard library (no fonttools); the generated header is
committed, so the normal build needs none of this.

Inter is licensed under the SIL Open Font License 1.1. The OFL permits bundling
and embedding; we ship the verbatim license at third-party/inter/LICENSE, and the
header carries an attribution comment with the font's copyright line and a pointer
to that license.

Generated (committed) outputs:
    third-party/inter/inter_font.h  compressed+base85 TTF as a C string
    third-party/inter/LICENSE       verbatim SIL Open Font License 1.1
"""

import io
import json
import pathlib
import shutil
import subprocess
import tempfile
import urllib.request
import zipfile

REPO = pathlib.Path(__file__).resolve().parent.parent
TOOL_SRC = REPO / "third-party/imgui/misc/fonts/binary_to_compressed_c.cpp"
TTF_IN_ZIP = "extras/ttf/Inter-Regular.ttf"
LICENSE_IN_ZIP = "LICENSE.txt"
SYMBOL = "inter"
OUT_DIR = REPO / "third-party/inter"


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=180) as resp:
        return resp.read()


def latest_release_zip_url():
    """Resolve the .zip asset of the most recent Inter release, with its tag."""
    rel = json.loads(fetch("https://api.github.com/repos/rsms/inter/releases/latest"))
    for asset in rel["assets"]:
        if asset["name"].lower().endswith(".zip"):
            return asset["browser_download_url"], rel["tag_name"]
    raise SystemExit("error: no .zip asset on the latest Inter release")


def copyright_line(license_text):
    """First 'Copyright' line of the OFL, used in the header's attribution."""
    for line in license_text.splitlines():
        if line.strip().lower().startswith("copyright"):
            return line.strip()
    raise SystemExit("error: no copyright line in Inter LICENSE")


def compress_to_base85(ttf, workdir):
    """Compile binary_to_compressed_c and run it on the TTF, returning its C output.

    The tool prints the input filename into a comment, so we run it from a temp
    dir on a cleanly named copy to keep absolute paths out of the committed file.
    """
    cxx = shutil.which("c++") or shutil.which("g++") or shutil.which("clang++")
    if not cxx:
        raise SystemExit("error: no C++ compiler found (need c++, g++, or clang++)")
    tool = workdir / "binary_to_compressed_c"
    subprocess.run([cxx, "-O2", str(TOOL_SRC), "-o", str(tool)], check=True)

    (workdir / "Inter-Regular.ttf").write_bytes(ttf)
    out = subprocess.run([str(tool), "-base85", "Inter-Regular.ttf", SYMBOL],
                         cwd=workdir, check=True, capture_output=True, text=True)
    return out.stdout


def attribution(version, notice):
    return (
        "// Generated by scripts/gen_font.py - do not edit.\n"
        "//\n"
        f"// Contains Inter ({version}, static Regular instance), stb-compressed with\n"
        "// third-party/imgui/misc/fonts/binary_to_compressed_c.cpp and base85-encoded.\n"
        f"// {notice}\n"
        "// Licensed under the SIL Open Font License 1.1; see third-party/inter/LICENSE.\n"
    )


def main():
    print("Resolving latest Inter release...")
    zip_url, version = latest_release_zip_url()
    print(f"  {version}: {zip_url}")

    print("Downloading release zip...")
    with zipfile.ZipFile(io.BytesIO(fetch(zip_url))) as zf:
        ttf = zf.read(TTF_IN_ZIP)
        license_text = zf.read(LICENSE_IN_ZIP).decode()
    print(f"  {TTF_IN_ZIP}: {len(ttf)} bytes")

    print("Compressing font...")
    with tempfile.TemporaryDirectory() as tmp:
        c_array = compress_to_base85(ttf, pathlib.Path(tmp))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "LICENSE").write_text(license_text)
    header = attribution(version, copyright_line(license_text)) + "#pragma once\n\n" + c_array
    (OUT_DIR / "inter_font.h").write_text(header)
    print(f"  header: {len(header)} bytes")

    print("Done:")
    print("  third-party/inter/inter_font.h")
    print("  third-party/inter/LICENSE")


if __name__ == "__main__":
    main()
